target-version = "py313"
line-length = 160
indent-width = 2
extend-exclude = [".vscode", ".idea", "__pycache__", ".python-version", ".ruff.toml", "ruff.toml", "setup.cfg", "pyproject.toml"]

[format]
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 120

[lint]
# D - Enable all `pydocstyle` rules, limiting to those that adhere to the Pep257 convention enabled via `convention = "pep257"` below
select = ["E501", "I", "D"]
ignore = ["D203","D204","D211","D212","D400","D406","D407","E266","C901"]

[lint.pylint]
# Maximum number of arguments for function / method
max-args = 20
# Maximum number of boolean expressions in a if statement
max-bool-expr = 10
# Maximum number of branch for function / method body
max-branches = 100
# Maximum number of locals for function / method body
max-locals = 15
# Maximum number of nested blocks for function / method body
max-nested-blocks = 5
# Maximum number of positional arguments allowed for a function or method definition
max-positional-args = 10
# Maximum number of public methods for a class (see R0904).
max-public-methods = 30
# Maximum number of return statements allowed for a function or method body
max-returns = 10
# Maximum number of statements in function / method body
max-statements = 1000

[lint.pydocstyle]
convention = "pep257"

[lint.mccabe]
max-complexity = 10