Name = "Từ điển Câu chuyện chữ Hán bằng tiếng Việt v1.0"
Description = "Từ điển Câu chuyện chữ Hán"
Source = "zh"
Target = "vi"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 3189
