Name = "Chinese Character Stories v1.0"
Description = "Chinese Character Stories based on the components"
Source = "zh"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 3189
