Name = "Từ điển Việt - Nga v1.0"
Description = "Từ điển Việt - Nga"
Source = "vi"
Target = "ru"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 35742
