Name = "Từ điển Việt - Nhật v1.0"
Description = "Từ điển Việt - Nhật"
Source = "vi"
Target = "ja"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 21614
