Name = "Từ điển Đức - Việt v1.0"
Description = "Từ điển Đức - Việt với các dạng từ"
Source = "de"
Target = "vi"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = "inflection-deu.tab"
Num_entries = 43634
