Name = "Từ điển Trung-Việt β (đại) v1.0"
Description = "Từ điển Trung-Việt β (cỡ đại) với nhiều chi tiết nhất. Bao gồm hơn 130k mục từ, phủ hết mục từ trong CCCE."
Source = "zh"
Target = "vi"
Version = "1.1"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
