Name = "Từ điển Việt - Nhật v1.0"
Description = "Anh - Việt"
Source = "ja"
Target = "vi"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 21896
