Name = "Từ điển WordNet v1.0"
Description = "Từ điển WordNet"
Source = "en"
Target = "en"
Version = "1.0"
Owner_Editor = "Wikipedia"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 154559
