Name = "CCCE Dictionary (thin) v1.0"
Description = "CCCE Dictionary (thin)"
Source = "zh"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 107334
