Name = "Cấu thành từ tiếng Trung v1.0"
Description = "Từ điển phân tích các chữ cái tiếng Trung thành các cấu thành"
Source = "zh"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 9145
