Name = "Chinese Thesaurus (mid) v1.0"
Description = "Chinese Thesaurus (mid size)"
Source = "zh"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 50129
