Name = "Từ điển Trung - Việt v1.0"
Description = "Từ điển Trung - Việt"
Source = "zh"
Target = "vi"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 161194
