Name = "Từ điển Anh - Việt v1.1"
Description = "Từ điển Anh - Việt với các dạng từ"
Source = "en"
Target = "vi"
Version = "1.1"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = "inflection-eng.tab"
Num_entries = 386600
