Name = "Từ điển Việt - Đức v1.0"
Description = "Từ điển Việt - Đức"
Source = "vi"
Target = "de"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 11922
