Name = "Từ điển Việt - Tây Ban Nha v1.0"
Description = "Từ điển Việt - Tây Ban Nha"
Source = "vi"
Target = "es"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 21608
