Name = "Từ điển Việt - Anh v1.0"
Description = "Từ điển Việt - Anh"
Source = "vi"
Target = "en"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 42155
