Name = "Từ điển Hàn - Việt - Hàn v1.0"
Description = "Từ điển Hàn - Việt - Hàn"
Source = "ko"
Target = "vi"
Version = "1.0"
Owner_Editor = "OVDP"
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 71947
