Name = "Từ điển Phật học Việt Anh - Minh Thông v1.0"
Description = "Từ điển Phật học Việt Anh - Minh Thông"
Source = "vi"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 9113
