Name = "Từ điển Phật Quang v1.0"
Description = "Từ điển Phật Quang"
Source = "vi"
Target = "vi"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 16973
