Name = "Từ điển Phật học Tinh tuyển v1.0"
Description = "Từ điển Phật học Tinh tuyển"
Source = "vi"
Target = "vi"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 2918
