Name = "Từ điển Phật học Anh-Hán-Việt v1.1"
Description = "Từ điển Phật học Anh-Hán-Việt"
Source = "en"
Target = "vi"
Version = "1.1"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = "inflection-eng.tab"
Num_entries = 3914
