Name = "Từ điển Phật học Việt Anh - Thiện Phúc v1.0"
Description = "Từ điển Phật học Việt Anh - Thiện Phúc"
Source = "vi"
Target = "en"
Version = "1.0"
Owner_Editor = ""
URL = "https://github.com/catusphan/dictionary"
Inflections = ""
Num_entries = 24767
